### ISSUE TITLE
Walking animation for low-res sprites link 404's

### ISSUE THREAD

**Issue by AUTplayed** [Siilwyn/awesome-pixel-art#12]
the link for Walking animation for low-res sprites has been removed: http://www.manningkrull.com/pixel-art/walking.php

**Comment by Siilwyn** [comment]
Ow shame, thank you for reporting.
Will need to find a good replacement, workaround for now is [viewing with the wayback machine](https://web.archive.org/web/20170919034246/http://www.manningkrull.com/pixel-art/walking.php).
