### ISSUE TITLE
Add more FOSS tools (free & opensource)

### ISSUE THREAD

**Issue by Symbian9** [Siilwyn/awesome-pixel-art#13]
- AzPainter (for Unix-like systems)
  - http://github.com/symbian9/azpainter
- mtPaint
  - https://github.com/matyler/mtPaint
- Slate
  - https://github.com/mitchcurtis/slate

**Comment by Symbian9** [comment]
- PixelArtShader for Blender 2.7x
  - https://github.com/kushi34123616bd/PixelArtShader

**Comment by Symbian9** [comment]
- pyqx
  - https://github.com/MikiLoz92/pyqx
- Import PixelArt addon for Blender 2.7x
  - https://github.com/panzi/blender-addon-import-pixelart

**Comment by Siilwyn** [comment]
Thanks for your suggestions! Note that I try to keep this list concise by only adding items that offer something different from the rest. Looking at these three tools: mtPaint looks unmaintained, AzPainter doesn't offer something different from GIMP and Slate looks like a good tool which in regards to being free and open source is similar to Piskel but as a native app.

But I never heard somebody use Slate, do you have experience with it? What would you say is awesome about it? Feel free to create a PR!

**Comment by Symbian9** [comment]
Lists of Pixel Art Programs 

- http://forums.gnomoria.com/index.php?topic=4508.0
- https://lospec.com/pixel-art-software-list

**Comment by Siilwyn** [comment]
@Wiadomy that tool is not mentioned anywhere in this issue... Anyway, pull requests are more than welcome! Provide a good reason why PyxelEdit is awesome and stands out from the other tools, please create a new issue to discuss this if needed.
