### ISSUE TITLE
Request to add to the Readme

### ISSUE THREAD

**Issue by rowtechshio** [Siilwyn/awesome-pixel-art#14]
Hi all,

I'm a beginner looking for an open source project to contribute to. I'd like to request to do some editing to the readme. I like to add some text flavor to the introduction and add to the text style as well.

Thanks,
Bradon

**Comment by Siilwyn** [comment]
Hello and welcome!

Great to have you on board. Feel free to create a pull request ([explanation](https://github.com/sindresorhus/awesome/blob/master/contributing.md#adding-something-to-an-awesome-list)) with the changes you have in mind! I'll review them and we can work from there.

If you have the time I would appreciate input on issue #8

**Comment by rowtechshio** [comment]
Of course I can work on issue #8 as well. I'll go ahead and comment on that thread to get things rolling. I should be able to start working on them both by tomorrow!
