### ISSUE TITLE
Add 'Feed' section?

### ISSUE THREAD

**Issue by Siilwyn** [Siilwyn/awesome-pixel-art#8]
:bulb: Add section with blogs, Twitter accounts, YouTube channels, Vimeo channels, etc. that provide an awesome variety of pixel art related content. So not just finished products but also tutorials, news and time lapses.
:warning: Should make clear distinction with the artists section or ditch this idea and put it all under the artists section.

Would need to have at least three items that would fit in this section, only have one for the moment:
- https://www.youtube.com/channel/UCsn9MzwyPKeCE6MEGtMU4gg

All input, ideas and suggestions are more than welcome!

**Comment by rowtechshio** [comment]
I can work on this as well as Issue #14. Should I find the content to post or is there already a list of them that is waiting to be integrated?

Side question, but you mention having at least 3 items that would fit in this section. It looks like the tutorials and content sections already exist. Are you referring to a time-lapse section?

Thanks,
Bradon

**Comment by Siilwyn** [comment]
There is no list unfortunately, we'll have to find awesome content.

I'm thinking of a new section called 'Feed' with content that people can subscribe to. Like news and video channels.

**Comment by rowtechshio** [comment]
Sure thing, feeds of updating content is something I'm always looking for online as well. I can look around and find a list of youtubers to start out with, and some blogs/tumblr outlets that post as well. I'm not sure what I'll find as far as news goes, should I find news on pixel art specifically or art news in general? (Like updates on new art supplies or programs)

**Comment by Siilwyn** [comment]
@rowtechshio as pixel art specific as possible.

I'm still not sure about the whole 'Feed' section because the 'Artists' section is a bit the same because it contains blogs. Thoughts on that?

Btw. this [YT channel](https://www.youtube.com/channel/UCsn9MzwyPKeCE6MEGtMU4gg) is a very good example of what I would consider awesome.

**Comment by rowtechshio** [comment]
I could change the Artists section to "Community" and have subsets for subreddits and websites, twitter and youtube news and artists, and the like. Just have it all under one "news feed" so to speak, as they all fall under relatively the same category.
